config/routes.rb
Rails.application.routes.draw do
  get 'admin/hacker_list'

  devise_for :admins
  devise_for :hackers
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hacker.rb
class Hacker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def hacker_list
  	@hackers = Hacker.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/hacker_list.html.erb
<h1>Hacker List</h1>
<table>
	<thead>
		<th>Email</th>
		<th>Join Date</th>
	</thead>
	<tbody>
		<% @hackers.each do |hacker| %>
			<tr><%= hacker.email %></tr>
			<tr><%= hacker.created_at.to_date %></tr>
		<% end %>
	</tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Welcome to my app!</p>
<p>
	<button id="modal-link">Steve Quote</button>
</p>
<div id="modal-background">
	<div id="modal-window">
		<p class="modal-text">Hi!</p>
		<a href="#" class="close">Close</a>
	</div>
</div>

app/views/layouts/_header.html.erb
<div>
		<%= link_to 'Sign in', new_hacker_session_path %>
		<%= link_to 'Sign up', new_hacker_registration_path %>
		<%= link_to 'Sign in as admin', new_admin_session_path %>
		<% if admin_signed_in? %>
			<%= link_to 'View Hacker List', admin_hacker_list_path %>
		<% end %>
	<div>
		<p class="notice">
			<%= notice %>
		</p>
		<p class="alert">
			<%= alert %>
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNewRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>